---
- name: mail - Setup mail alerts
  template:
    src: mail.j2
    dest: {{ monit_includes }}/mail
    owner: "{{ monit_owner_user }}"
    group: "{{ monit_owner_group }}"
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled
