---
- include_tasks: debian/pkg.yml
  tags: monit_pkg
  when: >-
    ansible_os_family == "Debian"
    and ((monit_version == "") or (monit_prebuilt_target == ""))

- include_tasks: redhat/pkg.yml
  tags: monit_pkg
  when: >-
    ansible_os_family == "RedHat"
    and ((monit_version == "") or (monit_prebuilt_target == ""))

- include_tasks: official/pkg.yml
  tags: monit_pkg
  when: (monit_version != "") or (monit_prebuilt_target != "")

- include_tasks: config.yml
  tags: monit_config

- include_tasks: monitors.yml
  tags: monit_monitors

- include_tasks: service.yml
  tags: monit_service
  when: monit_service != ""
