---
- name: monitors - Write monitors
  template:
    src: monitor.j2
    dest: "{{ monit_includes }}/{{ item.name }}"
    owner: "{{ monit_owner_user }}"
    group: "{{ monit_owner_group }}"
  with_items: "{{ monit_services }}"
  notify: restart monit

- name: monitors - Create facts directory
  file:
    path: "{{ monit_fact_dir }}"
    mode: 0755
    state: directory

- name: monitors - Registers configured monitors
  template:
    src: "monit.fact.j2"
    dest: "{{ monit_fact_dir }}/monit.fact"
    mode: 0644

- name: monitors - Reload facts
  setup:
    fact_path: "{{ monit_fact_dir }}"
    filter: "ansible_local"

- name: monitors - List configured monitors
  command: ls -1 {{ monit_includes }}
  register: monit_services_present
  changed_when: false

- name: monitors - Remove unused monitors
  file:
    path: "{{ monit_includes }}/{{ item }}"
    state: absent
  with_items: "{{ monit_services_present.stdout_lines | default([]) }}"
  when: monit_service_delete_unlisted and item|basename not in ansible_local.monit.monit_configured_services
  notify: restart monit
