---
- name: web - Setup webinterface
  template:
    src: webinterface.j2
    dest: "{{ monit_includes }}/webinterface"
    owner: "{{ monit_owner_user }}"
    group: "{{ monit_owner_group }}"
  notify: restart monit
